language: generic 
sudo: required
services:
    - docker

before install:
    - docker build -t rndjlnn/react-test -f ./client/dockerFile.dev ./client

script:
    - docker run -e CI=true rndjlnn/react-test npm test

after_success:
    - docker build -t rndjlnn/multi-client ./client
    - docker build -t rndjlnn/multi-nginx ./nginx
    - docker build -t rndjlnn/multi-server ./server
    - docker build -t rndjlnn/multi-worker ./worker
    # log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take images and push then to docker hub
    - docker push rndjlnn/multi-client
    - docker push rndjlnn/multi-nginx
    - docker push rndjlnn/multi-server
    - docker push rndjlnn/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: arn:aws:s3:::elasticbeanstalk-us-east-2-665827257144
    bucket_path: docker-multi
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY
    on:
        branch: master